volumes:
    repo:

services:
    app:
        container_name: docker-tdm
        restart: always
        stdin_open: true # -i
        tty: true        # -t
        
        ports:
            - 5900:5900
            - 6080:6080
        
        image: shayes/docker-tdm
        build:
            context: .
            dockerfile: Dockerfile
            args:
                TDM_REPO:
        
        volumes:
            - repo:/app/TwitchDropsMiner/
            - ./scripts/init.sh:/init.sh
        
        environment:
            VNCPASS:
            TDM_REPO:
    
    restarter:
        container_name: docker-tdm-restarter
        image: docker:cli
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
            - ./scripts/restarter.sh:/restarter.sh
        entrypoint: "/restarter.sh"
        restart: always

