volumes:
    repo:

services:
    app:
        stdin_open: true # -i
        tty: true        # -t
        
        ports:
            - 5900:5900

        build:
            context: .
            dockerfile: Dockerfile
            args:
                TDM_REPO:
        
        volumes:
            - repo:/app/TwitchDropsMiner/
            - ./:/app/host/
        
        command: bash ./host/docker-init.sh

        environment:
            VNCPASS:
            TDM_REPO:


