volumes:
    repo:

services:
    app:
        container_name: docker-tdm
        restart: always
        stdin_open: true # -i
        tty: true        # -t
        
        ports:
            - 5900:5900
        
        image: shayes/docker-tdm
        build:
            context: .
            dockerfile: Dockerfile
            args:
                TDM_REPO:
        
        volumes:
            - repo:/app/TwitchDropsMiner/
            - ./:/app/host/
        
        #command: bash ./host/docker-init.sh

        environment:
            VNCPASS:
            TDM_REPO:


